//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenSistemaTG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int IdEquipo { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public string NoSerie { get; set; }
        public Nullable<int> Existencia { get; set; }
        public string Proveedor { get; set; }
        public int IdAlmacen { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
